### ISSUE TITLE
Folder structure

### ISSUE THREAD

**Issue by isBatak** [NinoMaj/carousel-virtualized#11]
https://github.com/NinoMaj/carousel-virtualized/blob/cc254d02a80d9ea7284ffe81908064ed9812441c/src/index.ts#L3
`src/components/Slider/Slider.tsx` could be changed to `src/components/Slider/index.tsx` and then you won't have this repetition, you could import it just like this 
`import { Slider } from './components/Slider';`

**Comment by NinoMaj** [comment]
That's true, issue is when all files are named index.js it's a bit harder to find the file you are looking for. Let's say you have 10 files opened in you editor and all of them are named index.js. Even one of Ryan Dahl Node.js regrets was supporting index.js :) -> https://www.youtube.com/watch?v=M3BM9TB-8yA
Also, since we are using ts, I am leveraging 'auto import' so longer paths don't bother me.
Closing for now since it's not a major issue, but we can change it letter.
